Traceback (most recent call last):
  File "C:\Users\arajen\Anaconda3\envs\jbook\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\arajen\Anaconda3\envs\jbook\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\arajen\Anaconda3\envs\jbook\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\arajen\Anaconda3\envs\jbook\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\arajen\Anaconda3\envs\jbook\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\arajen\Anaconda3\envs\jbook\lib\site-packages\nbclient\client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\arajen\Anaconda3\envs\jbook\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\arajen\Anaconda3\envs\jbook\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import the particular module of the pvlib library
from pvlib import pvsystem

# CEC PV Module Database
cec_mod_db = pvsystem.retrieve_sam('CECmod')

# Size of the database
print(cec_mod_db.shape)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_13436/905169781.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Import the particular module of the pvlib library[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [1;32mfrom[0m [0mpvlib[0m [1;32mimport[0m [0mpvsystem[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [1;31m# CEC PV Module Database[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mcec_mod_db[0m [1;33m=[0m [0mpvsystem[0m[1;33m.[0m[0mretrieve_sam[0m[1;33m([0m[1;34m'CECmod'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'pvlib'
ModuleNotFoundError: No module named 'pvlib'

